#ifndef SCENE_H
#define SCENE_H

#include <algorithm>
#include <type_traits>

#include "./bounding.hpp"
#include "./renderer_state.hpp"
#include "../lib/include/glad/gl.h" // generated by https://github.com/Dav1dde/glad , required to load system OpenGL API implementation

namespace sdf {


  class Scene {

    public:

      //using volume_type = std::variant<AABB, bounding_sphere>;
      //using volume_container = std::map<unsigned int, volume_type>;
      //using volume_child_pair = std::pair<std::optional<volume_type>&, std::optional<bounding_volume::child_type>&>;

      //volume_container volumes_old;

      /*
      template <class T>
      void add_volume(const T volume) {
        volume_type new_volume = volume;
        volumes_old.insert(std::make_pair(volume.ID, new_volume));
      }
      */

      std::map<unsigned int, sdf::AABB> volumes;

      void add_volume(sdf::AABB volume);

      void render(Shader &s, Shader &l, glm::vec3 position) const;

      void update();

      sdf::AABB &operator[](const unsigned int id) {
        return volumes.at(id);
      } 

  };

} // namespace sdf

#endif

