#ifndef SCENE_H
#define SCENE_H

#include <algorithm>
#include <type_traits>

#include "./bounding.hpp"
#include "./renderer_state.hpp"
#include "../lib/include/glad/gl.h" // generated by https://github.com/Dav1dde/glad , required to load system OpenGL API implementation

namespace sdf {


  class Scene {

    public:

      std::map<unsigned int, sdf::AABB> volumes;

      void add_volume(sdf::AABB volume);

      void render(Shader &s, Shader &l, glm::vec3 position) const;

      void update();

      sdf::AABB &operator[](const unsigned int id) {
        return volumes.at(id);
      } 

  };

} // namespace sdf

#endif

