#ifndef TEXTURE_H
#define TEXTURE_H

#include "../lib/include/glad/gl.h" // generated by https://github.com/Dav1dde/glad , required to load system OpenGL API implementation
#include <glm/glm.hpp>

#include <iostream>
#include <string>

#define FONT_UNIT GL_TEXTURE1

unsigned int blank_texture(glm::vec2 size, GLenum unit);

unsigned int texture_from_image(std::string image_path, GLenum unit);

#endif
