#include <iostream>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include "../lib/include/glad/gl.h" // generated by https://github.com/Dav1dde/glad , required to load system OpenGL API implementation
#include "../inc/start_opengl.hpp"
#include "../inc/shader.hpp"
#include "../inc/scene.hpp"
#include "../inc/events.hpp"
#include "../inc/player.hpp"
#include "../inc/renderer_state.hpp"
#include "../inc/level.hpp"
#include "../inc/gui.hpp"

extern struct renderer_state_container renderer_state;

int main() {

  std::cout << std::boolalpha;

  GLFWwindow* window = loader::load_gl();
  glfwSetCursorPosCallback(window, event::game::mouse_callback);
  //glfwSwapInterval(0);

  if (window == NULL) {
    std::cerr << "error: window not initialised" << std::endl;
    exit(1);
  }

  auto exit_button_func = []() -> void {
    exit(0);
  };

  auto start_button_func = [&window]() -> void {
    level::Level test_level("./level/test.level");
    test_level.play(window);
  };

  gui::Button exit_button(gui::pixel_cast<NDC>(0, 555), gui::pixel_cast<SIZE>(40, 45), exit_button_func);
  gui::Button start_button(gui::pixel_cast<NDC>(300, 220), gui::pixel_cast<SIZE>(180, 35), start_button_func);

  gui::Font font("./res/bitmap_font1.png");
  gui::Label exit_label(gui::pixel_cast<NDC>(0, 560), "X", font, gui::pixel_cast<SIZE>(40, 40));
  gui::Label start_label(gui::pixel_cast<NDC>(300, 225), "START!", font, gui::pixel_cast<SIZE>(30, 25));

  gui::Page title_screen;
  title_screen.add(exit_button).add(start_button).add(exit_label).add(start_label);


  for (;;) {

    glClearColor(0.1f, 0.1f, 0.6f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    int state = glfwGetMouseButton(window, GLFW_MOUSE_BUTTON_LEFT);
    if (state == GLFW_PRESS) {

      for (auto &b : title_screen.buttons) {
        if (b.contains(gui::get_cursor_position(window))) {
          b.button_func();
        }
      }

    }

    title_screen.render();

    glfwSwapBuffers(window);
    glfwPollEvents();

  }

  std::cout << "program terminated successfully\n";

  glfwTerminate();

  return 0;

}
