#include <iostream>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include "../lib/include/glad/gl.h" // generated by https://github.com/Dav1dde/glad , required to load system OpenGL API implementation
#include "../inc/start_opengl.hpp"
#include "../inc/shader.hpp"
#include "../inc/scene.hpp"
#include "../inc/events.hpp"
#include "../inc/player.hpp"
#include "../inc/renderer_state.hpp"
#include "../inc/level.hpp"
#include "../inc/gui.hpp"
#include "../inc/game_menu.hpp"

extern struct renderer_state_container renderer_state;

int main() {

  std::cout << std::boolalpha;

  GLFWwindow* window = loader::load_gl();
  glfwSetCursorPosCallback(window, event::game::mouse_callback);
  glfwSwapInterval(1); // capped frame rate at refresh rate (0 means uncapped)

  if (window == NULL) {
    std::cerr << "error: window not initialised" << std::endl;
    exit(1);
  }

  gui::GUI menu("title_screen");

  gui::Page level_screen = game::get_level_selector(&menu, window, "./level/");
  gui::Page title_screen = game::get_title_screen(&menu, window);
  gui::Page fail_screen = game::get_fail_screen(&menu, window);

  menu 
    << std::make_pair("level_selector", level_screen) 
    << std::make_pair("title_screen", title_screen)
    << std::make_pair("fail_screen", fail_screen);

  for (;;) {

    glClearColor(0.3f, 0.1f, 0.6f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    event::menu::process_input(window, &menu);

    menu.render(); // all of the actual game is accessed via this method. keeps the main function concise (unlike in previous iterations)

    glfwSwapBuffers(window);
    glfwPollEvents();

  }

  std::cout << "program terminated successfully\n";

  glfwTerminate();

  return 0;

}
